src/Convex.jl
src/atoms/huber.jl
src/atoms/logdet.jl
src/problems.jl
test/run_tests.jl
test/test2.jl
test/test_exp_and_sdp.jl
test/test_other.jl

new atoms for ee364a as per #40 
- huber loss
- log det

huber loss and log det atoms

---

REQUIRE
docs/installation.rst
docs/solvers.rst
src/solution.jl
src/solver_info.jl
test/REQUIRE

Now that SCS is released, coverage should go near 80%
Also this makes us ready for 0.0.3 / EE364A

make SCS default solver

---

REQUIRE
docs/installation.rst
docs/solvers.rst
src/solution.jl
src/solver_info.jl
test/REQUIRE
test/runtests.jl

Ref: https://github.com/JuliaLang/METADATA.jl/pull/2008
There's obviously ways in which this can be better, but I think this is fine for now.

Update to not have any solver installed by default

---

src/Convex.jl

Julia 0.3.7
```julia
julia> tic(); using Convex; toc()
elapsed time: 1.518227565 seconds
1.518227565
```
Julia 0.4-, before this change
```julia
julia> tic(); using Convex; toc()
elapsed time: 1.232959917 seconds
1.232959917
```
After this change
```julia
julia> tic(); using Convex; toc()
elapsed time: 0.260348828 seconds
0.260348828
```

Enable precompile

---

REQUIRE
src/Convex.jl
src/conic_form.jl

This seems to do the trick.
Closes #106
CC @emreyamangil

use OrderedDict to generate deterministic variable ordering

---

src/problems.jl
src/solution.jl

Ref JuliaOpt/MathProgBase.jl#91
Don't merge until new MPB is about to be released.
Tests are passing locally on ``mpb0.4`` branch of MPB and solvers.

updates for MPB 0.4

---

test/test_sdp.jl

This gets the unit tests passing for me on the lastest Julia 0.5

fix tests on julia 0.5

---

examples/antidiag.jl

as well as deprecation warnings on Uint64 and flipud

got TypeError running n_queens example with 0.4.2

---

src/solution.jl

This PR fixes populate_solution! bug if the solver cannot return values after failure (Mosek), checked with Mosek after this fix too. CC @madeleineudell 
Closes #130

solution fix

---

src/atoms/sdp_cone/nthroot_det.jl
test/test_sdp.jl

@madeleineudell - I added some tests based on the D-optimal experiment design problem. One of them doesn't pass, and I can't figure out why. 
`    @fact evaluate(sgeomean_eig(V * diagm(lam1) * V')) => roughly(p1.optval, TOL)
`
I evaluate the objective of the problem and it doesn't return the optimal value of the problem.

added sgeomean_eig tests

---

REQUIRE
src/constraints/sdp_constraints.jl

Let's see if this passes travis. CC @chriscoey
Closes #140

update for new SDP format

---

src/atoms/affine/multiply_divide.jl
test/test_socp.jl

Fix tests for multiplication change from #148

---

docs/operations.rst
src/atoms/sdp_cone/lambda_min_max.jl

arguments to lambdamin and max need not be PSD

---

src/atoms/affine/stack.jl
src/atoms/second_order_cone/norm.jl

I might be having a brain fart, but does this address #145? Tests seem to pass locally

fix for julia 0.5

---

src/Convex.jl

See previous attempt at #98 and #99. Works locally on Julia 0.5.

Try enabling precompilation again.

---

examples/optimization_with_complex_variables/povm_simulation.ipynb

Implements the qubit case of the method described in arXiv:1609.06139.

Example of using convex optimization for solving qubit POVM simulability

---

src/atoms/affine/multiply_divide.jl

Closes https://github.com/JuliaOpt/Convex.jl/issues/174

Remove debugging output

---

README.md
src/atoms/lp_cone/abs.jl

Norm_1 correction

---

examples/optimization_with_complex_variables/Fidelity in Quantum Information Theory.ipynb

This example is inspired from a lecture of John Watrous in the course on Theory of Quantum Information

Adding Fidelity in Quantum Information Theory example

---

README.md

Aplologies! Last PR resulted in some weird characters in README file. This PR fixes it.

Removed unwanted character in readme

---

docs/complex-domain_optimization.rst
src/atoms/affine/conjugate.jl

redefined conj as element-wise complex conjugate

---

src/expressions.jl
test/test_utilities.jl

Add axes and lastindex to fix regression in indexing

---

src/solution.jl
src/utilities/show.jl

Update more uses of == nothing to use ===

---

docs/complex-domain_optimization.rst

Just a small update so the example runs

Docs: Update example

---

src/atoms/lp_cone/min.jl
test/test_lp.jl

match neg(x) docs definition

---

.travis.yml
Project.toml
REQUIRE
test/REQUIRE

Summary of changes:
* Remove `REQUIRE` and `test/REQUIRE`
* Drop Julia 0.7 support
* Use semver specifiers for package compatibility bounds
* Add Julia 1.1 and clean up `.travis.yml` a bit
* Set `Project.toml` version to 0.12.0 in preparation for a new release

Drop 0.7, add version to Project.toml, misc housekeeping

---

docs/make.jl

Should fix #305, cc @ericphanson

Fix repo specification for doc deployment

---

docs/examples_literate/portfolio_optimization/portfolio_optimization2.jl

now that quadform is a scalar. Also, Plots.jl has changed how legends should be formatted (row vector).

small update of example

---

README.md
docs/src/solvers.md

Thanks @migarstka for a pure Julia solver :)

Add COSMO to docs

---

test/runtests.jl

Let us see if the bug persists.

Try allowing the matrix frac test on SCS

---

.travis.yml
NEWS.md
Project.toml
docs/src/reference.md
src/solution.jl
src/variable.jl
test/test_utilities.jl

Fixes #403 
Not totally sold on the name, but I wanted to distinguish it from `verbose`...

Add `silent_solver` keyword argument and tweak CI

---

NEWS.md
Project.toml
src/atoms/affine/conjugate.jl
test/definitions.jl

closes #416 
Great catch @dstahlke!

fix `conj`

---

NEWS.md
Project.toml
src/atoms/lp_cone/sumlargest.jl
src/atoms/sdp_cone/sumlargesteigs.jl
src/problem_depot/problems/lp.jl
src/problem_depot/problems/sdp.jl
test/test_utilities.jl

allow `sumlargest(x,k)`, `sumsmallest(x,k)`, and `sumlargesteigs(x,k)` for `k=0` 

---

src/solution.jl
test/test_utilities.jl

I didn't test this. I just noticed from a post on dicourse: https://discourse.julialang.org/t/convex-jl-set-some-configurations-e-g-maximum-iteration-number-etc/57724

Use MOI.instantiate to create a new optimizer

---

src/problem_depot/problems/lp.jl

fix the tests for lp_dual_abs_atom

---

docs/src/installation.md

I had to do this to avoid the error message
Pkg.update ERROR: UndefVarError: Pkg not defined
which was resolved by 
julia> using Pkg
beforehand.

Fix installation process steps

---

docs/src/advanced.md

Closes #291 
Closes #234
Closes #229

[docs] fix warmstart example

---

docs/examples_literate/general_examples/lasso_regression.jl

This makes the lasso_regression example work again (after the lastest Convex/SCS changes). I also simplified one or two things.
Closes #485

fix lasso_regression (example)

---

Project.toml
docs/src/release_notes.md
src/atoms/affine/stack.jl
src/conic_form.jl

Change Dict -> OrderedDict

---

src/MOI_wrapper.jl
test/MOI_wrapper.jl

Add support for objective to MOI wrapper

---

src/atoms/lp_cone/abs.jl
src/atoms/lp_cone/dotsort.jl
src/atoms/lp_cone/max.jl
src/atoms/lp_cone/maximum.jl
src/atoms/lp_cone/min.jl
src/atoms/lp_cone/minimum.jl
src/atoms/lp_cone/sumlargest.jl

Tidy src/atoms/lp_cone

---

src/atoms/second_order_cone/geomean.jl
src/atoms/second_order_cone/huber.jl
src/atoms/second_order_cone/norm.jl
src/atoms/second_order_cone/norm2.jl
src/atoms/second_order_cone/qol_elementwise.jl
src/atoms/second_order_cone/quadform.jl
src/atoms/second_order_cone/quadoverlin.jl
src/atoms/second_order_cone/rationalnorm.jl

Tidy src/atoms/second_order_cone

---

README.md

Add JuMP example to README.md

---

src/atoms/affine/AdditionAtom.jl
test/test_atoms.jl

Test AdditionAtom

---

src/atoms/affine/DiagAtom.jl
src/atoms/affine/DiagMatrixAtom.jl
src/atoms/affine/HcatAtom.jl
src/atoms/affine/SumAtom.jl
test/test_atoms.jl

Add tests for src/atoms/affine

---

src/Convex.jl
src/constraints/GreaterThanConstraint.jl
src/constraints/LessThanConstraint.jl
src/deprecations.jl
src/problem_depot/problems/socp.jl
test/test_utilities.jl

Deprecate strict inequalities

---

src/Convex.jl
src/atoms/exp_+_sdp_cone/LogDetAtom.jl
src/atoms/exp_cone/EntropyAtom.jl
src/atoms/exp_cone/ExpAtom.jl
src/atoms/exp_cone/LogAtom.jl
src/atoms/exp_cone/LogSumExpAtom.jl
src/atoms/exp_cone/RelativeEntropyAtom.jl
test/test_atoms.jl

Add tests for src/atoms/exp

---

src/atoms/sdp_cone/EigMaxAtom.jl
src/atoms/sdp_cone/EigMinAtom.jl
src/atoms/sdp_cone/MatrixFracAtom.jl
test/test_atoms.jl

Add tests for atoms/sdp_cone

---

src/atoms/affine/MultiplyAtom.jl
src/atoms/affine/ReshapeAtom.jl
src/atoms/lp_cone/MaxAtom.jl
src/atoms/second_order_cone/QolElemAtom.jl
src/problem_depot/problems/affine.jl
test/test_atoms.jl

Add tests for affine/MultiplyAtom and ReshapeAtom

---

src/reformulations/conv.jl
src/reformulations/dot.jl
src/reformulations/inner_product.jl
src/reformulations/norm.jl
src/reformulations/partialtranspose.jl
src/reformulations/quadform.jl
src/reformulations/transpose.jl
test/test_atoms.jl
test/test_utilities.jl

Add tests for src/reformulations

---

docs/src/operations.md
src/Convex.jl
src/atoms/exp_cone/EntropyAtom.jl
test/test_atoms.jl

Add entropy_elementwise

---

docs/src/developer/contributing.md

[docs] clarify atoms must be mutable

---

src/constraints/EqualToConstraint.jl
src/constraints/ExponentialConeConstraint.jl
src/constraints/GreaterThanConstraint.jl
src/constraints/LessThanConstraint.jl
src/constraints/PositiveSemidefiniteConeConstraint.jl
src/constraints/SecondOrderConeConstraint.jl
test/runtests.jl
test/test_constraints.jl

Add tests for src/constraints

---

test/test_problem_depot.jl

Enable lieb_ando test for Clarabel

---

src/solution.jl
test/test_utilities.jl

@ericphanson I have some questions about this one. I'll comment in-line.

Tidy src/solution.jl

---

src/Context.jl
src/MOI_wrapper.jl
test/MOI_wrapper.jl

Add a second cache for bridged variables

---

src/problem_depot/problems/socp.jl
src/reformulations/quadform.jl
test/test_atoms.jl

Closes #585 
Introduced by https://github.com/jump-dev/Convex.jl/pull/399
@ericphanson does this make sense?

Fix quadform with fixed variables that are modified between solves

---

docs/src/developer/contributing.md

Closes #521
I don't know how important this section is, but #521 doesn't need to block a release.

[docs] clarify section of contributing.md

---

docs/src/manual/advanced.md
src/solution.jl
test/test_problem_depot.jl
test/test_utilities.jl

Closes #518 
Closes #233
I'll comment something in-line

Add support for setting MOI.VariablePrimalStart

---

docs/src/manual/types.md
test/test_utilities.jl

[docs] clarify broadcasting in constraint documentation

---

docs/src/manual/operations.md
src/Convex.jl
src/atoms/sdp_cone/RootDetAtom.jl
test/test_atoms.jl

Add RootDetAtom

---

src/atoms/AbsAtom.jl
test/test_atoms.jl

Improve performance of `AbsAtom`

---

src/atoms/GeoMeanAtom.jl

Improve performance of GeoMeanAtom

---

src/atoms/RelativeEntropyAtom.jl
src/constraints/GenericConstraint.jl
test/test_atoms.jl
test/test_constraints.jl

Extracted from https://github.com/jump-dev/Convex.jl/pull/617

Add GenericConstraint{RelativeEntropyCone} support

---

src/complex_operate.jl
src/operate.jl
src/real_operate.jl
test/test_atoms.jl

Fix tests for constant complex-valued atoms

---

src/solution.jl
test/test_constraints.jl

x-ref https://github.com/jump-dev/Convex.jl/pull/631/files#r1591749619

Report compilation stats when silent_solver=false

---

src/utilities/show.jl
test/test_utilities.jl

Fix show for problems with variables containing constraints

---

docs/src/examples/optimization_with_complex_variables/Fidelity in Quantum Information Theory.jl

old link is 404, I believe this is the same PDF but on Prof Watrous's new website.

Update link Fidelity in Quantum Information Theory example

---

docs/make.jl
docs/src/changelog.md
docs/src/manual/performance_tips.md
docs/styles/config/vocabularies/jump-dev/accept.txt
src/ComplexTape.jl

I didn't want to restart CI on #678 so I made a separate PR. I believe it will only build the docs here which is nice.

Add 686 to news

---

.github/workflows/docs.yml

x-ref https://github.com/JuliaTime/TimeZones.jl/pull/459#issuecomment-2123418212

Build docs on Julia v1.10

---

README.md

this was pointed out as unnecessarily complicated by @matbesancon

Use two constraints in example problem

---

README.md

In https://github.com/jump-dev/Convex.jl/pull/688 I forgot to update the comment as well, oops!

Tweak readme example

---

src/supported_operations.jl
test/test_atoms.jl

Support AbstractArray in relative_entropy and log_perspective

---

Project.toml
docs/src/changelog.md

Prep for v0.16.3

---

docs/src/examples/general_examples/optimal_advertising.jl

Closes https://github.com/jump-dev/Convex.jl/issues/722

[docs] use vcat in optimal_advertising.jl
