jump-dev/Convex.jl

src/atoms/second_order_cone/quad_form.jl
I was running into problems with quad_form. My A matrix passed the is_symmetric test (tolerance of 1e-6), but the eigenvalues had very small complex parts. The pairwise compare operator in Julia does not like this, so it would choke. I just added a call to real around the eigenvalues. This happens after the check for symmetric matrices, so it should only happen when numerical issues cause small complex parts.
=> update quad_form to handle (slightly) complex eigenvalues

src/atoms/affine/index.jl, src/atoms/dot_sort.jl
~~This doesn't get Convex passing on 0.4, but, it gets it a bit further.~~
I didn't even know the original behavior worked for that `any` in `dot_sort`,
```
```
but this change seems to at least match the old behavior.
=> Fix Convex on Julia 0.4

src/Convex.jl
Reverts JuliaOpt/Convex.jl#98
Woops. I thought I tested it, but apparently not, getting
```
Affine Atoms
- negate atom
ERROR: LoadError: LoadError: LoadError: TypeError: call: in new, expected Dict{Tuple{Symbol,UInt64},Dict{UInt64,Union{AbstractArray{T,N},Number}}}, got Dict{Tuple{Symbol,UInt64},Dict{UInt64,Union{AbstractArray{T,N},Number}}}
in call at /Users/idunning/.julia/v0.4/Convex/src/conic_form.jl:70
in conic_problem at /Users/idunning/.julia/v0.4/Convex/src/problems.jl:110
in solve! at /Users/idunning/.julia/v0.4/Convex/src/solution.jl:32
in solve! at /Users/idunning/.julia/v0.4/Convex/src/solution.jl:10
in anonymous at /Users/idunning/.julia/v0.3/Convex/test/test_affine.jl:12
in context at /Users/idunning/.julia/v0.4/FactCheck/src/FactCheck.jl:417
in anonymous at …
```
=> Revert "Enable precompile"

src/atoms/exp_cone/relative_entropy.jl, test/test_exp.jl
Pull request against the ``relative_entropy`` branch. Fixed some bugs, added some tests, and adjusted the definition of ``log_perspective(x,y)`` to be ``y*log(x/y)`` which reads better to me.
=> relative entropy tests and tweaks

src/atoms/affine/add_subtract.jl, src/atoms/affine/multiply_divide.jl, src/conic_form.jl, src/constraints/constraints.jl, src/dcp.jl
This takes care of these warnings when loading the package...
```
WARNING: module Convex should explicitly import - from Base
WARNING: module Convex should explicitly import + from Base
WARNING: module Convex should explicitly import * from Base
WARNING: module Convex should explicitly import == from Base
WARNING: module Convex should explicitly import <= from Base
WARNING: module Convex should explicitly import < from Base
WARNING: module Convex should explicitly import >= from Base
WARNING: module Convex should explicitly import > from Base
WARNING: module Convex should explicitly import .+ from Base
WARNING: module Convex should explicitly import .- from Base
WARNING: module Convex should explicitly import / from Base
WARNING: module Convex should explicitly import .* from Base …
```
=> Explicitly import operators from Base

test/runtests_single_solver.jl
Let's see if this passes tests now. Ref https://github.com/JuliaOpt/Convex.jl/issues/109
=> params tests only work with SOCP solvers

src/constraints/sdp_constraints.jl
=> Fix deprecation warnings due to use of "int()" instead of "round(Int,)"

src/problems.jl
This sort of splatting got really slow (i.e., takes many minutes) in Julia 0.4 if you have thousands of constraints. Using ``collect`` seems to resolve the performance issue.
CC @emreyamangil
=> avoid splatting in problem construction

src/atoms/affine/stack.jl, test/test_socp.jl
Convex.jl shouldn't really be hijacking vcat, but this at least fixes the issue.
CC @emreyamangil
=> hack to fix #117

src/atoms/affine/diag.jl
x = Variable(4,5)
Presently
y_1 = diag(x,4)
AbstractExpr with
head: diag
size: (0, 1)
sign: Convex.NoSign()
vexity: Convex.AffineVexity()
does not give error but it should be giving ideally as we can't have the kth diagonal where k is greater than or equal to both the number of rows and columns.
This PR fixes the present bug.
y_2 = diag(x,4)
**ERROR: Bounds error in calling diag**
=> Correcting diag atom

src/atoms/affine/multiply_divide.jl
`*` is matrix multiplication, not elementwise
todo: add a test
=> don't return elementwise square for matrix A*A

src/atoms/second_order_cone/quadform.jl
Currently, `quadform()` does not support sparse matrices. Changed `is_symmetric` function input type to `::AbstractArray`, which is a supertype for both `::AbstractSparseArray` and `::DenseArray`
=> Added support for sparse matrices to quadform

src/atoms/second_order_cone/norm.jl
This resolves the following warning on 0.5:
```
julia> using Convex
WARNING: Method definition norm(Convex.AbstractExpr, Symbol) in module Convex at /home/mlubin/.julia/v0.5/Convex/src/atoms/second_order_cone/norm.jl:45 overwritten at deprecated.jl:49.
```
``norm(,::Symbol)`` isn't defined in Julia 0.4 or 0.5. ``vecnorm`` is used for the Frobenius norm.
=> remove old norm(,::Symbol) method

README.md
This is how we do it in Optim, and it can avoid this problem: https://discourse.julialang.org/t/convex-optimisation-over-complex-variables/1388 when the front page readme is the "latest" readme.
=> Explicitly provide stable and latest docs links.

REQUIRE
The MPB 0.6 release was only breaking for the default solver functionality. No changes seem to be needed in Convex.jl.
=> bump upper bound on MathProgBase

src/solver_info.jl
Load solvers from `Base.LOAD_PATH` when not found in `Pkg.dir()`
=> Load solvers from Base.LOAD_PATH

docs/examples.rst, docs/operations.rst, src/atoms/affine/kron.jl, src/atoms/lp_cone/abs.jl, src/constant.jl
* Defined kron for (constant, AbstractExpr)
* Also kron now accepts complex numbers
* Added link to complex-domain example in docs
* Fixed warning for abs2
@peterwittek this PR solves the error in accepting complex numbers as an argument to kron and now the first argument in kron need not to be a constant.
=> Any argument in kron can be an abstractExpr

test/test_params.jl
The regularization-parameters in "fix multiplication" was badly chosen, resulting in numerical problems (`o2-o1  ≈ 3e-12` when `eps=1e-12`was set for SCS). The regularization only works reasonable in the range 0.8 to 0.85 as shown in the plot. I changed the test to reflect the expected behavior for larger and smaller regularization parameters.
=> Fixed robustness of test in "test_params.jl"

src/constant.jl
These lines causes `OutOfMemoryError` on large problems because of the broadcast (I believe sparse broadcast is still suffering from performance issues). The proposed change uses an explicit iterator over the elements instead. The problem is easily reproduced by, for example:
```julia
n = 50000
x0 = randn(2n)
A = sprandn(n, 2n, 0.0001)
b = A*x0
x = Variable(2n)
p = minimize(norm(A*x-b), sum(x) == sum(x0))
```
all tests passes locally on
Julia Version 0.6.1-pre.0
Commit dcf39a1* (2017-06-19 13:06 UTC)
=> Avoid OutOfMemoryError

test/REQUIRE, test/old.jl, test/oldperf.jl, test/runtests.jl, test/runtests_single_solver.jl, test/test_affine.jl, test/test_complex.jl, test/test_exp.jl, test/test_exp_and_sdp.jl, test/test_int.jl, test/test_lp.jl, test/test_params.jl, test/test_sdp.jl, test/test_socp.jl, test/test_utilities.jl, test/warmstart.jl
Replace `FactCheck` by testsets.
=> use testsets

.travis.yml, test/REQUIRE, test/runtests.jl
We've seen some inconsistent test failures, seemingly always involving tests that use values computed via `rand`. To make these tests more reliable, we can seed the stream using `srand`. Note that it's `Random.seed!` on 0.7 and up, but Convex's current master branch does not support anything other than 0.6. On a related note, this also removes Travis testing on Julia master, as there is no chance of it working as-is.
I will re-tag v0.7.0 once this is merged. The 0.6 failure on JuliaCIBot for the current v0.7.0 tag failed due to these issues.
=> Seed random number stream to improve test reliability

.travis.yml, REQUIRE
As it stands, this package does not support Julia 0.7. In order to get a final 0.6-compatible tag into METADATA, we need to apply an upper bound. See https://github.com/JuliaLang/METADATA.jl/pull/19091.
=> Upper bound Julia at 0.7-

src/atoms/affine/sum.jl, src/atoms/sdp_cone/operatornorm.jl, src/atoms/second_order_cone/norm.jl, src/atoms/second_order_cone/norm2.jl, src/expressions.jl, test/test_sdp.jl, test/test_socp.jl
The behavior of `norm(x, p)` for matrices changed in https://github.com/JuliaLang/julia/pull/27401 to be the same as `norm(vec(x), p)` and `vecnorm` was removed. The previous behavior of `norm` for matrices is now captured by `opnorm`. This updates our extensions to these functions to match, and emits deprecation warnings as appropriate.
As a somewhat related change, this also deprecates the positional dimension argument to `sum` in favor of keyword arguments, in keeping with Base.
Properly fixes #231, which was already closed, and should fix an error in SchattenNorms observed with JuliaCIBot (see [here](https://juliarun-ci.s3.amazonaws.com/1ab1a9c14bbccf791c72724313bf4b57c7f479f9/SchattenNorms_with_pull_request_of_Convex_on_julia_0_7.log)).
=> Fix use of norm and remove vecnorm

src/atoms/affine/add_subtract.jl
Instead of splatting the input into a broadcast call, we can use broadcast in reduction with a single call to `mapreduce`.
=> Improve performance for evaluate(::AdditionAtom)

src/atoms/affine/dot.jl, test/test_affine.jl
The `vecdot` function was deprecated in favor of `dot` in https://github.com/JuliaLang/julia/pull/27401; `dot` on matrices now treats them like vectors.
The change here updates our extension of `dot` to match this behavior and deprecates `vecnorm`.
=> Remove vecdot

docs/solvers.rst, src/problems.jl, src/solver_info.jl
This seems like the first step to dropping the `DEFAULT_SOLVER` behaviour and getting rid of the following warning:
```
┌ Warning: Package Convex does not have ECOS in its dependencies:
│ - If you have Convex checked out for development and have
│   added ECOS as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Convex
```
which causes precompilation to fail on 1.0. Related to #244
=> Deprecated default solvers

src/problems.jl
```
julia> using Convex
WARNING: Method definition (::Type{Convex.Problem})(Symbol, Convex.AbstractExpr) in module Convex at /home/alex/.julia/packages/Convex/MLj0c/src/problems.jl:34 overwritten at /home/alex/.julia/packages/Convex/MLj0c/src/problems.jl:45.
```
This was caused by providing a default value of `nothing` for the `model` argument in the `Problem` constructor, which ends up creating a two-argument method that is also created further down by virtue of using default values.
By simply removing the default value for `model`, we remain at feature parity with the methods prior to the change and we don't overwrite anything.
=> Fix method overwrite warning when loading the package

src/atoms/affine/add_subtract.jl, src/atoms/affine/diag.jl, src/atoms/affine/index.jl, src/atoms/affine/multiply_divide.jl, src/atoms/affine/reshape.jl, src/atoms/affine/stack.jl, src/atoms/affine/transpose.jl, src/atoms/lp_cone/dotsort.jl, src/atoms/lp_cone/sumlargest.jl, src/constant.jl, src/constraints/soc_constraints.jl, src/expressions.jl, src/problems.jl, src/variable.jl
They're defined to be the same thing but the implementation of the former is 2x slower than the latter. Rather than improving the code we can just combine them.
Further, we can simplify the implementation of `length` by calling `length` directly on the underlying value for `Constant`s.
=> Deprecate get_vectorized_size in favor of length

src/atoms/affine/index.jl, src/variable.jl
The compiler likes this a lot more than `== nothing`.
=> Use === for checks against nothing

REQUIRE, src/Convex.jl, src/conic_form.jl, src/constraints/exp_constraints.jl, src/constraints/sdp_constraints.jl, src/constraints/soc_constraints.jl, src/variable.jl, test/test_utilities.jl
* Make ConicObj its own type. This reduces the amount of type piracy in the package. Currently the package defines multiplication of a sparse matrix and an ordered dictionary, as one example.
* Replace the dependency on DataStructures, which is quite large, with one on OrderedCollections. This is a lighter weight package and we're only using one piece of it anyway.
* Change some `Array` definitions to `Vector` as appropriate (the compiler likes it better) and add `@inbounds` annotations to a few loops that fill the arrays.
=> Make ConicObj its own type

src/constant.jl, test/test_utilities.jl
This allows for more expressive condition checking using dispatch, as complex numbers, real numbers, or arrays thereof can be handled as separate methods.
~~This also limits the types that can be accepted as constant values to scalars, vectors, and matrices. Previously this was assumed but not actually checked.~~
Fixes #264.
=> Parameterize Constant on the type of its value

.gitignore, Project.toml, src/solver_info.jl, test/runtests.jl
This adds a Project.toml file which records dependencies and compatibility information and it removes the vestigial uses of Pkg for hacking optional dependencies.
=> Add a Project file, remove vestigial Pkg uses

docs/advanced.rst, docs/loop.rst, docs/quick_tutorial.rst, docs/types.rst
I tried to update the docs to reflect that `solve!` requires a solver be passed now. I used `SCSSolver()` in the code for concreteness.
=> Updated docs to reflect that one has to pass a solver to `solve!`.

src/utilities/iteration.jl, test/test_utilities.jl
Fixed iteration (and thus broadcast over variables). Previous behavior was
```julia
x = Variable(4)
[xi.inds for xi in x] == [1:1, 1:1, 2:2, 3:3]
```
which for example resulted in wrong results in the following cases
```julia
constraints = x .>= [1,2,3,4] #[x[1] >=1, x[1] >=2, x[2]>=3, x[3]>=4]
sum([xi for xi in x]) # x[1]+x[1]+x[2]+x[3]
```
Also made sure that `iterate` does not depend on indexing the variable out of range.
It previously accessed `x[1]` even when `length(x)=0`.
I also removed the elements of `x` from the state, I see no reason for passing them around.
There is still the (existing) unexpected behavior of `evaluate(sum([xi for xi in x]))` being a vector.
I didn't fix this but made sure the test will pass if it is fixed.
As a side note (I can add an issue if it is not …
=> Fixed iterate over Variable

src/conic_form.jl, test/test_utilities.jl
We're using the value of `objectid` to store values in `ConicObj`, but `objectid` returns `UInt32` on 32-bit systems. Currently `ConicObj` only accepts indexing operations with `UInt64` keys, which causes a method error on 32-bit systems. This was an oversight when introducing `ConicObj` as its own type.
Fixes #272
=> Allow indexing into ConicObj with any Integer

src/atoms/affine/kron.jl, test/test_affine.jl
Fixes #267, #209. The dimensions of `kron(A,B)` should be the same as the dimensions of `kron(B,A)`. I just copied the working method to fix the broken one, and put the `isreal` check on the value again. That check is mentioned in <https://github.com/JuliaOpt/Convex.jl/issues/204#issuecomment-315590295>, seems to be working around the strange behavior `Convex.jl` has with complex-typed but `isreal`-true values.
=> Fix `kron` dimension bug, add simple test

src/atoms/affine/multiply_divide.jl, test/test_affine.jl
Fixes #274 and #266.
I saw a suspicious adjoint and changed it to a transpose, and suddenly #274 worked (and the tests pass). 
I have to say, I don't entirely understand how this works. I think what's going on is that matrices are stored as long vectors, which I think corresponds to the map in (1.127) of [TQI], and then matrix multiplication can be represented on the vectorized space by the formula 1.132 of [TQI], which indeed uses the transpose, not the adjoint.
[TQI]: https://cs.uwaterloo.ca/~watrous/TQI/TQI.1.pdf
But I'd appreciate a more appropriate reference!
=> Fix right-multiply bug, add simple test

src/atoms/affine/partialtrace.jl, test/test_sdp.jl
The partial trace was implemented using just `kron`, `*`, and `sum`, which are already atoms, so we actually don’t need `PartialTraceAtom`. Additionally, `evaluate` and `conic_form!` were implemented separately but via the same algorithm (and the version in `evaluate` was incorrect), so I’ve replaced it all with a generic function following the same method. I also fixed the test (to see why the new version of the test is right, note the solution to the SDP should satisfy the constraint), and added some additional tests.
Fixes #281.
=> Fix and simplify partial trace, add more tests

src/Convex.jl, src/constraints/constraints.jl, src/variable.jl, test/test_utilities.jl
I saw there were some  global variables which I thought should be declared `const`. I wasn't sure how to check for improvement, so I ran `@time include("test/runtests.jl");` three times on master and with these changes, each on a fresh Julia session (after running it once to compile).
With these changes:
1.   2.271733 seconds (1.45 M allocations: 95.721 MiB, 8.59% gc time)
2.   2.238526 seconds (1.45 M allocations: 96.115 MiB, 2.97% gc time)
3.   2.084262 seconds (1.45 M allocations: 95.699 MiB, 3.14% gc time)
On master:
1.   2.532733 seconds (1.45 M allocations: 95.759 MiB, 2.42% gc time)
2.   3.026007 seconds (1.45 M allocations: 96.404 MiB, 7.01% gc time)
3.   2.388227 seconds (1.45 M allocations: 95.752 MiB, 2.65% gc time)
There's a lot of variance, but it does seem faster. I think it …
=> Make global variables constant

src/atoms/affine/stack.jl, test/test_utilities.jl
Fixes https://github.com/JuliaOpt/Convex.jl/issues/223.
I'm not sure if this change is OK or not. On the one hand, the tests pass. On the other hand, it must be here for a reason; maybe this change will break some obscure edge case. In the latter case though, it would be nice if we had a test to show we need this override (or even better, find a different resolution to such an edge case without overriding `Base.vect`).
I thought I'd make the pull request to open a discussion at least.
P.S. sorry for the barrage of pull requests; no rush to address these, I'm just trying to work through the issue backlog a bit.
=> Remove Base.vect override

src/atoms/affine/multiply_divide.jl, test/runtests.jl, test/test_const.jl, test/test_socp.jl
Fixes #166, fixes  #228, resolves #139 
`x.children[1].head == :constant` was incorrectly used to check if `x.children[1]` is constant, which doesn’t happen when `x.children[1]` is a function of a constant; instead, `ConstVexity()` should be used instead, like it is in the rest of the file. This was causing the second branch to be taken when creating the conic form for multiplication, i.e. the code would assume that `x.children[2]` must be the constant variable when in fact it could be the non-constant variable, which was then sometimes giving incorrect results when using `fix!`, as shown in #166. 
Another issue is that `x.value` was used to access the value of a constant expression. When `x` was not simply a constant variable (instead say a `fix!`’d variable that was multiplied by a …
=> Fix some issues with `fix!`

src/variable.jl, test/test_const.jl
Currently, if you `fix!` twice and then `free!`, you end up with a variable with `AffineVexity` but `:fixed`, because `free!` only removes the last `:fixed` and still changes the convexity. 
On release and on master with ECOS, the test I added segfaults (which seems strange), and on release and master with SCS, the third test simply fails (the solver returns `NaN`).
=> Allow calling `fix!` twice in a row

README.md, src/solution.jl
Looks like I forgot to update the README in https://github.com/JuliaOpt/Convex.jl/pull/271. I also went ahead and added a `using ECOS` to the error message for `solve!(problem)`, since it looks like that being missing caused some confusion in #300. Maybe we should switch it to SCS though? Or switch all the SCS stuff in the docs to ECOS. I had simply chosen SCS in #271 because it was an open source solver I had been using, but that choice was pretty arbitrary, and I don't mind switching it all to ECOS. Or maybe it's nice that the docs and error message use two different solvers to show more of the possibilities :).
Fixes https://github.com/JuliaOpt/Convex.jl/issues/300
=> Update README to reflect that you need to pass a solver

src/variable.jl, test/test_const.jl
Convex only has 2-dimensional objects but it works hard to promote and demote user types from scalars and vectors to 2-dimensional objects and back. This pull request is to help maintain that illusion when calling `fix!` on a "scalar" variable (i.e., "size(x)==(1,1)"). 
A problem similar to the test I added is what motivates the change. This test fails on master; specifically, the second test with `evaluate` throws the following:
```julia
Test threw exception
Expression: ≈(evaluate(tr(p * x)), 2.0, atol=TOL)
DimensionMismatch("A has dimensions (1,1) but B has dimensions (2,2)")
Stacktrace:
[1] gemm_wrapper!(::Array{Float64,2}, ::Char, ::Char, ::Array{Float64,2}, ::Array{Float64,2}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/matmul.jl:439 …
```
=> Fix `fix!` for scalar parameters with multiplication

src/variable.jl, test/test_const.jl
The `Array{Float64}` conversion seems to have been in Convex since the start (before the introduction of complex numbers), so I think it is just overdue for an update. I introduced the scalar `Float64` conversion in https://github.com/JuliaOpt/Convex.jl/pull/303, following the array case, which got me thinking about this conversion and realizing it would fail in the complex case. (Also, I think I should have used `convert` instead of the constructor for consistency.)
I think these conversions are just so that if someone does `fix!(x, 1)` everything works ok.
=> Allow `fix!`ing complex variables to complex numbers

src/atoms/affine/real_imag.jl, src/constraints/signs_and_sets.jl, test/test_sdp.jl
Addressing #198. I believe this check is incorrectly checking for `ComplexVariable()` rather than `ComplexSign()` which results in some complex values in the constraints list.
Besides this small fix, I have added the bugged case from #198 in the tests. Please let me know if you want me to change or add something.
=> Fixing bug for complex semidefinite cases

src/variable.jl, test/test_const.jl
Another annoying `fix!` bug; since we check the dimensions, but Convex expects vectors to be size `(d,1)`, we get errors.
=> Fix `fix!` for vector inputs

.travis.yml
This prevents also benchmarking again after merging a PR, which is slow and prevents Travis from running other jobs.
=> Only benchmark on PRs

LICENSE.md, Project.toml, docs/Project.toml, docs/src/advanced.md, src/Convex.jl, src/utilities/show.jl, src/utilities/tree_interface.jl, src/utilities/tree_print.jl, test/test_utilities.jl
I find myself usually ignoring the printing of problems, because it's quite verbose while not being very informative. Here, I propose new printing that I think helps with both problems.
Old printing:
```julia
julia> x = Variable(4, 1)
Variable of
size: (4, 1)
sign: NoSign()
vexity: AffineVexity()
julia> p = minimize(dotsort(x, [1, 2, 3, 4]), sum(x) >= 7, x >= 0, x <= 2, x[4] <= 1)
Problem:
minimize AbstractExpr with
head: dotsort
size: (1, 1)
sign: NoSign()
vexity: ConvexVexity()
subject to
Constraint:
>= constraint
lhs: AbstractExpr with
head: sum
size: (1, 1)
sign: NoSign()
vexity: AffineVexity()
rhs: 7
vexity: AffineVexity()
Constraint:
>= constraint
lhs: Variable of
size: (4, 1)
sign: NoSign()
vexity: AffineVexity()
rhs: 0
vexity: AffineVexity()
Constraint:
<= constraint
lhs: Variable …
```
=> Improve printing of problems, constraints, and variables

src/Convex.jl, src/atoms/affine/stack.jl, src/conic_form.jl, src/constraints/constraints.jl, src/problems.jl, src/solution.jl, src/variable.jl, src/variable_conic_form.jl, test/test_utilities.jl
Addresses half of #83 by removing one of the two global variables Convex uses. (Edit: second half addressed in a later commit in this PR; see https://github.com/JuliaOpt/Convex.jl/pull/322#issuecomment-526923615).
Currently (i.e. on master), `id_to_variables` is a global dictionary associating the `id_hash` field of Variables to the Variable object itself, forming a global registry of variables. This allows one nice feature of Convex: Variables don't have to be explicitly added to a problem, since they are accessible to all problems via the global registry. To populate the registry, each variable must add itself to `id_to_variables` upon creation.
The aim here is to replace this global registry with a local one for each problem. This has the advantage that when all the problems using a …
=> Remove global variables

test/test_lp.jl, test/test_socp.jl
I've checked the dual variables either analytically or via cvx (and different solvers) in matlab.
=> add more tests, in particular for dual variables, cf. #290

docs/src/advanced.md, src/utilities/show.jl, src/utilities/tree_print.jl, test/test_utilities.jl
Closes #342. This now means our vendored `print_tree` method is ahead of https://github.com/Keno/AbstractTrees.jl/pull/38 by a commit (adding `maxwidth`).
I'm thinking it's probably OK to have this method vendored long-term, since it's nice to be able to control our own printing. I don't think it poses any compatibility problems, since `print_tree` isn't really relied on within the AbstractTrees codebase; it's just a utility. So I don't think there's a problem if `Convex.TreePrint.print_tree` is a different function than `AbstractTrees.print_tree`. We still have interop since we extend `AbstractTrees.children` which is the real interface method.
=> Add `MAXWIDTH` for printing

NEWS.md, src/constant.jl, src/problem_depot/problems/sdp.jl, src/problem_depot/problems/socp.jl, src/variable.jl, test/test_utilities.jl
The fix is to just have `evaluate(x::Variable)` and `evaluate(c::Constant)` yield scalars and vectors when appropriate. (Not sure why I was getting lots of test failures last time I tried, as I mentioned in #341; I lost that local branch).
=> Fix #341, add news

src/Convex.jl
This was removed in #357 along with a lot of other exports, but I don't think I meant to remove `Constraint`. It's pretty useful for doing things like
```julia
constraints = Constraint[]
...
push!(constraints, ...)
...
problem = minimize(objective, constraints)
```
which doesn't work with `constraints = []` due to the way the`Problem` constructors are typed. I think those should be revisited along with other API stuff in #346 later, but for now let's just add back the export. This export being missing also breaks one of the examples; I'm not sure why CI didn't catch that.
=> export `Constraint`

docs/src/advanced.md, src/Convex.jl, src/dcp.jl, src/utilities/show.jl, test/test_utilities.jl
Fixes https://github.com/JuliaOpt/Convex.jl/issues/362
I'm not a big fan of globals (and I spent some time getting rid of them in #322), but since we emit this warning even on things like `x = Variable; y = Variable(); x*y`, there doesn't seem like a good place to pass in an argument `warn=false`. Arguably we could only do the check when calculating the `vexity` of a `Problem`, and then pass warning info through the problem constructor. (We would need to also make sure you can see the check before starting a solve, etc..)
However, (1) the way the `vexity` of a `Problem` is written currently is a little strange and I'd prefer not to mess with it yet, and (2) it might be helpful that we are very eager to warn on non-DCPness (i.e., on `x*y` instead of waiting for the user to put that inside …
=> Allow disabling DCP warnings

src/Convex.jl
Thanks to @vtjnash on #multithreading who pointed out the atomics don't do anything, because we aren't using `atomic_not!` to flip the boolean one, for example. He emphasized that atomics are relations, not objects, and it's the act of flipping the boolean that could be atomic (i.e. so you could get the current value and negate that, and then set that to be the value, all while knowing another thread hasn't changed the value inbetween getting and setting the value).
Here, however, we don't need to get and set together (atomically), we are just setting, so there is no need for an atomic (and it doesn't do anything).
I think we could use locks if we were concerned about multiple threads changing these values at once, but one just shouldn't do that (just choose the settings at the start of …
=> Switch atomics to refs

docs/src/advanced.md, src/Convex.jl, src/utilities/show.jl, test/test_utilities.jl
Follow-up to https://discourse.julialang.org/t/convex-jl-how-to-print-full-variable-id/35917
=> Allow setting max print width of IDs via `Convex.MAXDIGITS`.

.gitignore, Project.toml, src/problems.jl, test/test_utilities.jl
Closes #380 
The definition of this function hasn't really changed since it was introduced in 2014 in https://github.com/JuliaOpt/Convex.jl/commit/9c346819492f4c3bf551845bc1400fc8eda0c139, but I think it worked at that point since at that point, `+` for constraints called `append!`, so it was more of a `+=` than a `+`, and did the right thing for `add_constraints!` (but I guess the wrong thing for a `+` method). It looks like the `+` method was fixed in https://github.com/JuliaOpt/Convex.jl/commit/337bb96c17d4ce95130473cf7547ba2648a4bed0 (also in 2014) to append to an empty array, which then broke `add_constraints!`.
Quite an old bug! This must have been frustrating for some users over the years. Thanks @riccardomurri for reporting it.
=> Fix `add_constraint!`

docs/examples_literate/mixed_integer/aux_files/antidiag.jl
Typo revealed by https://travis-ci.org/github/JuliaOpt/Convex.jl/jobs/673075558
I am very puzzled why docs stages have been passing, since this should have failed every time since I made the typo a few months ago.
=> Fix example n queens

docs/src/index.md
I'm not 100% sure this is the best place for it, but I wanted it somewhere people would see it fairly quickly, because I think it makes it more clear what exactly Convex.jl is doing and why DCP warnings are important. As I've worked on #393, I've realized the obvious fact that the central/only thing Convex.jl does is automatic application of extended formulations, and I didn't find that to be completely clear from the docs, so I wanted to write about it somewhere central. 
The other reason for adding this is to make the issue with non-DCP problems more clear. I actually haven't seen too many issues where people are solving non-DCP problems and getting confused by the fact that the results are wrong, but I do think it can be confusing why that happens. For example, I thought for awhile …
=> Discuss extended formulations in docs

NEWS.md, Project.toml, src/atoms/affine/diagm.jl, test/test_utilities.jl
Fixes #401. The `diagm` method accepting a vector was taken away in Julia 1.0 and added back in Julia 1.1, so we should add it back here too.
=> Fix `diagm(x)`

docs/src/operations.md, src/atoms/sdp_cone/nuclearnorm.jl, src/atoms/sdp_cone/sumlargesteigs.jl, src/problem_depot/problems/affine.jl, src/problem_depot/problems/sdp.jl
- nuclearnorm and sumlargesteigs now support complex variables.  This only required making the auxiliary variables complex when the input is complex.
- sumlargesteigs had a condition A ⪰ 0 which was not appropriate.  This would require the input variable to be positive semidefinite.  A unit test shows it works correctly even when A is not.
- I've also included the unit test for my recent hcat fix.  Looks like this wasn't merged into master.
=> Fixed nuclearnorm and sumlargesteigs for complex variables

NEWS.md, Project.toml, src/variable.jl, test/test_utilities.jl
Fix #426 
I am not sure why we had the previous method, and I'm not totally sure this is the same (in particular, I'm not sure when `x.value` references the same array as the input to `set_value!(x, v)` with convert vs when it makes a copy). But it's definitely wrong to hardcode `Float64`s or `Complex{Float64}`s here. I'll think about this more tomorrow.
=> fix bad conversion

src/atoms/second_order_cone/quadform.jl, src/problem_depot/problems/socp.jl
This follows this thread on discourse : https://discourse.julialang.org/t/regresion-eigvals-of-bigfloat-symmetric-matrices-does-not-work-anymore/63947
After understanding that the algorithm did not need to call eigvals, I tweaked it here: Since A is supposed to be a matrix of values, this should be equivalent while still working for weird types.
=> More efficient and less intrusive `quadform`

src/atoms/affine/index.jl, src/problem_depot/problem_depot.jl, src/problem_depot/problems/sdp.jl
Fixing the issue #447 (simplifying a one-element vector or matrix to a scalar). In addition, updating the syntax for choosing the optimizers in the docstring examples for run_tests() and benchmark_suite().
=> Fixing the issue #447 and updating the examples in docstrings for run_tests() and benchmark_suite()

src/atoms/exp_cone/logsumexp.jl, test/test_utilities.jl
Resolves #461.
Please refer to [this article](https://gregorygundersen.com/blog/2020/02/09/log-sum-exp/) how it makes `logsumexp` evaluation numerically stable.
=> Improve numerical stability of `logsumexp`

Project.toml, src/utilities/tree_print.jl
I've recently done a major overhaul of AbstractTrees.jl which will be part of the upcoming v0.4 release for that package.  Convex.jl is unique in that it is the only registered dependency of AbstractTrees.jl which uses the soon-to-be-deprecated functions `treekind` and `IndexedTree`.
It seems that Convex.jl contains a re-implementation of `print_tree` because of a problem that dates back to AbstractTrees.jl v0.2.  At first, I completely removed this re-implementation in favor of the current AbstractTrees implementation, but later realized that it has since diverged from `AbstractTrees.print_tree` even in v0.3.  In particular, while `maxdepth` has worked fine for a while, we do not have a `maxwidth`.  There are also some small differences in the exact printed forms.
Instead, I've removed …
=> remove deprecated AbstractTrees calls

src/atoms/affine/index.jl, test/test_utilities.jl
Allows for cartesian indexing for variables. Can change this to `AbstractExpr` if preferred.
=> add cartesian indexing

Project.toml, docs/src/release_notes.md, src/atoms/affine/stack.jl
Fixes #512 
Closes #513 
Closes #514 
Non-breaking alternative to #513. Since this isn't breaking, we probably should do it even if we want something like that.
=> Less piracy of `hcat` and `vcat`

src/Convex.jl, src/MOI_wrapper.jl, src/conic_form.jl, test/MOI_wrapper.jl
The goal of this PR is to provide
```julia
using JuMP
model = Model(() -> Convex.Optimizer(SCS.Optimizer()))
```
where the nonlinear constraints and objective will be reformulated into conic constraints for SCS.
=> Add MOI optimizer

src/problem_depot/problems/sdp.jl
closes #510
I believe this was fixed by #504, though I'm not sure how
=> add test for issue 510

docs/src/operations.md
This PR adds a line to `docs/src/operations.md` to cover the `relative_entropy(x, y)` (KL divergence) function, as requested in this issue: https://github.com/jump-dev/Convex.jl/issues/499
----
- Unfortunately, I was unable to build the docs locally to double-check for syntax errors: 
```text
ERROR: LoadError: `makedocs` encountered errors (:cross_references, :example_block). Terminating build before rendering.
```
- I notice that `entropy(x)` and `relative_entropy(x)` have opposite signs, despite the former being a special case of the latter. Any interest in a PR fixing this? Which one should flip? This would be a breaking change in either case.
=> Add `relative_entropy` to operations documentation

benchmark/alternating_minimization.jl, docs/examples_literate/general_examples/basic_usage.jl, docs/examples_literate/supplemental_material/paper_examples.jl, docs/src/release_notes.md, src/atoms/second_order_cone/norm.jl, src/problem_depot/problems/socp.jl
=> finish norm transition

src/Convex.jl, src/problems.jl, test/test_utilities.jl
=> Add write_to_file

src/atoms/affine/add_subtract.jl, src/atoms/affine/conjugate.jl, src/atoms/affine/conv.jl, src/atoms/affine/diag.jl, src/atoms/affine/diagm.jl, src/atoms/affine/dot.jl, src/atoms/affine/index.jl, src/atoms/affine/inner_product.jl, src/atoms/affine/multiply_divide.jl, src/atoms/affine/partialtrace.jl, src/atoms/affine/partialtranspose.jl, src/atoms/affine/real_imag.jl, src/atoms/affine/reshape.jl, src/atoms/affine/stack.jl, src/atoms/affine/sum.jl, src/atoms/affine/trace.jl, src/atoms/affine/transpose.jl
Just some small formatting changes, mainly so I have an excuse to read through and understand the code.
=> Tidy src/atoms/affine

src/atoms/exp_+_sdp_cone/logdet.jl, src/atoms/exp_cone/entropy.jl, src/atoms/exp_cone/exp.jl, src/atoms/exp_cone/log.jl, src/atoms/exp_cone/logsumexp.jl, src/atoms/exp_cone/relative_entropy.jl
=> Tidy src/atoms/exp

src/solution.jl, test/test_utilities.jl
I think I initially was using this code for debugging at some point in #504, but it was untested and bitrotted. Here I've added a test, I guess we could also export it and add it to the release notes. Alternatively we could delete it.
=> remove internal function `latex_formulation`

src/Convex.jl, src/MOI_wrapper.jl, src/problem_depot/problems/lp.jl, src/problem_depot/problems/sdp.jl, src/problems.jl, src/solution.jl, test/test_utilities.jl
This is a breaking change because `minimize(value, constraints)` no longer turns into a `satisfy` problem with `p.optval === nothing`.
=> [breaking] Fix setting constant objective function

docs/src/examples/general_examples/basic_usage.jl, docs/src/examples/mixed_integer/binary_knapsack.jl, docs/src/examples/mixed_integer/n_queens.jl, docs/src/examples/mixed_integer/section_allocation.jl, src/deprecations.jl, src/problem_depot/problems/mip.jl, src/problem_depot/problems/sdp.jl, src/variable.jl, test/test_utilities.jl
@ericphanson thoughts on `:Bin` vs `BinVar`? I assume your long-term plan was to deprecate the symbols? They're pretty brittle and the docs don't mention the Symbol approach.
=> Tidy src/variable.jl

docs/src/changelog.md, src/MOI_wrapper.jl, src/atoms/exp_cone/LogSumExpAtom.jl, src/atoms/lp_cone/DotSortAtom.jl, src/atoms/lp_cone/MinAtom.jl, src/atoms/lp_cone/MinimumAtom.jl, src/atoms/lp_cone/SumLargestAtom.jl, src/constraints/LessThanConstraint.jl, src/problem_depot/problems/affine.jl, src/problem_depot/problems/lp.jl, test/test_constraints.jl
x-ref https://github.com/jump-dev/Convex.jl/pull/590
=> [breaking] Fix a<=b to return a-b in Nonpositives instead of b-a in Nonnegatives

docs/src/changelog.md
The renaming hasn't been released so that's still how they are called in the current release
=> Rename to old names in changelog

src/constraints/GenericConstraint.jl
I think a default fallback returning `true` is incorrect. Since the constraint is not added when it is constant, we should check that it is feasible otherwise the infeasibility is silently ignored and the resulting status is incorrect.
=> Replace is_feasible by distance_to_set

src/constraints/GenericConstraint.jl, test/test_constraints.jl
I'm not sure we should allow matrices with more than one columns to be constrained to SOC. We can have for a user coming up for a good motivation and leave it as error at least for now.
=> Add default set_with_size

src/atoms/second_order_cone/QolElemAtom.jl, src/atoms/second_order_cone/QuadOverLinAtom.jl, src/constraints/GenericConstraint.jl, test/test_atoms.jl, test/test_constraints.jl
Going to continue after https://github.com/jump-dev/Convex.jl/pull/600 is merged
=> Use MOI.RotatedSecondOrderCone in QuadOverLinAtom

src/atoms/affine/HcatAtom.jl, src/atoms/affine/VcatAtom.jl, test/test_atoms.jl
=> Add VcatAtom

src/atoms/QuantumEntropyAtom.jl, src/atoms/QuantumRelativeEntropyAtom.jl, src/atoms/TraceLogmAtom.jl, src/atoms/TraceMpowerAtom.jl, test/test_atoms.jl
Tidying and tests related to https://github.com/jump-dev/Convex.jl/pull/604
=> Tidy SDP atoms from CVXQUAD

src/atoms/EntropyAtom.jl, src/atoms/ExpAtom.jl, src/atoms/LogAtom.jl, src/problem_depot/problems/exp.jl
Generalizes #613 to the other atoms that uses exponential cone constraints in the same way.
closes #613 
closes #254 
addresses the first three items of #614
=> Improve performance of `ExpAtom`, `LogAtom`, and `EntropyAtom`

src/VectorAffineFunctionAsMatrix.jl, src/atoms/QolElemAtom.jl
=> Improve performance of QolElemAtom

src/atoms/HuberAtom.jl, src/real_operate.jl, src/solution.jl, test/test_atoms.jl
Addresses https://github.com/jump-dev/Convex.jl/issues/616 in the real case only. In the complex case unfortunately I found many issues, too many to address in this PR. Some would be addressed similarly to the change for `new_conic_form!(context::Context{T}, e::RelativeEntropyAtom)`, where `GenericConstraint` nicely handles the constant case, but direct `MOI_add_constraint` does not.
(The issues here are not really correctness bugs, but rather errors one would get if for some reason they had constant values rather than variables in some atoms, such as if you `fix!`'d a variable).
=> Test conic forms for constant values

src/atoms/IndexAtom.jl, src/atoms/VcatAtom.jl, test/test_atoms.jl
here is my attempt at #611
closes #611 
closes #603
=> Special-case getindex on VcatAtom

docs/src/examples/optimization_with_complex_variables/power_flow_optimization.jl, src/atoms/IndexAtom.jl, src/problem_depot/problems/affine.jl, test/test_atoms.jl
fixes #509 
There _could_ be other issues like this out there, but at least this fixes that particular one, and I can't quite think of others off the top of my head.
=> [breaking] scalar row indexing produces column vector

benchmark/254.jl, benchmark/alternating_minimization.jl, src/atoms/MultiplyAtom.jl, src/constant.jl, src/solution.jl, test/test_utilities.jl
Before:
```julia
julia> include("alternating_minimization.jl");
┌ Info: Running with Convex.jl...
└   (m, n, k) = (125, 125, 3)
3.573375 seconds (482.01 k allocations: 4.005 GiB, 14.71% gc time, 2.11% compilation time)
┌ Info: Running with JuMP...
└   (m, n, k) = (125, 125, 3)
1.746994 seconds (11.50 M allocations: 965.324 MiB, 9.38% gc time, 16.74% compilation time)
Test Summary: | Pass  Total  Time
Same results  |    2      2  0.0s
julia> include("alternating_minimization.jl");
┌ Info: Running with Convex.jl...
└   (m, n, k) = (500, 500, 5)
zsh: killed     julia --project
```
After:
```julia
julia> include("alternating_minimization.jl")
┌ Info: Running with Convex.jl...
└   (m, n, k) = (125, 125, 3)
0.891868 seconds (481.78 k allocations: 374.011 MiB, 10.03% compilation time)
┌ Info: …
```
=> Allow SparseMatrixCSC in Constant

src/reformulations/conv.jl, test/test_atoms.jl, test/test_utilities.jl
```julia
julia> using Convex, BenchmarkTools
julia> x = rand(100_000);
julia> y = Variable(200);
julia> @btime conv($x, $y)
```
gives:
```
1.286 s (56 allocations: 1.04 GiB) # master
562.229 ms (37 allocations: 1.64 GiB) # PR
```
So 2x speed, but 1.6x allocations. I think it's a win overall, though not huge. Aimed at https://github.com/jump-dev/Convex.jl/issues/376
=> improve performance of `conv`

src/constraints/GenericConstraint.jl, test/test_constraints.jl
Closes #630
One possible solution to discuss.
* The `head` method is reasonable.
* The `vexity` method is up for debate. There are arguments for and against.
=> Add default fallbacks for head and vexity with MOI sets

test/Project.toml, test/runtests.jl
closes #639 
This revealed 6 ambiguities:
```julia
julia> Aqua.test_ambiguities(Convex)
6 ambiguities found. To get a list, set `broken = false`.
Ambiguity #1
Convex.Problem{T}(head::Symbol, objective::Union{Nothing, Convex.AbstractExpr}) where T<:Real @ Convex ~/Convex.jl/src/problems.jl:12
Convex.Problem{T}(head::Symbol, objective::Convex.AbstractExpr, constraints::Convex.Constraint...) where T<:Real @ Convex ~/Convex.jl/src/problems.jl:186
Possible fix, define
Convex.Problem{T}(::Symbol, ::Convex.AbstractExpr) where T<:Real
Ambiguity #2
getindex(x::Convex.AbstractExpr, I::AbstractVector{Bool}) @ Convex ~/Convex.jl/src/atoms/IndexAtom.jl:116
getindex(x::Convex.VcatAtom, inds::AbstractVector{<:Real}) @ Convex ~/Convex.jl/src/atoms/VcatAtom.jl:103
Possible fix, define …
```
=> Add Aqua.jl to the tests

src/atoms/VcatAtom.jl, src/constraints/GenericConstraint.jl, src/problems.jl, src/reformulations/quadform.jl, test/runtests.jl, test/test_atoms.jl
=> Fix ambiguities found by Aqua

docs/src/examples/mixed_integer/aux_files/antidiag.jl, docs/src/manual/advanced.md, src/Context.jl, src/MOI_wrapper.jl, src/constant.jl, src/constraints/GenericConstraint.jl, src/expressions.jl, src/solution.jl, src/utilities/show.jl, src/variable.jl, src/variable_template.jl, test/test_utilities.jl
We are using `objectid` as our hash, since there are no collisions thanks to the Julia runtime. We are using this as keys in dictionaries inside the `Context` object. However, an `IdDict` is exactly a dict that uses `objectid` for lookup. This also makes making new AbstractVariables a bit easier, although they still need to be mutable. (Before they had to be mutable and you had to set the `id_hash` yourself).
I don't expect this to necessarily have any performance implications, but `IdDict`s should be quite fast (since there's no hashing involved), and I think this should reduce the likelihood of bugs. E.g. I noticed in `ComplexConstant` we were generating the `id_hash` randomly (for some reason), which does have the chance of collision. We are still fairly type unstable, as before.
I …
=> [breaking] Cleanup the `Context` object: remove `id_hash`, simplify dictionaries

src/problems.jl, test/test_atoms.jl, test/test_utilities.jl
Take II at #310 
See also #636
=> Add support for using Problem as an atom

docs/src/developer/contributing.md, src/atoms/QuantumRelativeEntropyAtom.jl, src/atoms/TraceLogmAtom.jl, src/atoms/TraceMpowerAtom.jl, src/constraints/GenericConstraint.jl, src/reformulations/quadform.jl, src/reformulations/transpose.jl
I tried to ensure that #654 fixed the last issue here by checking each usage of `evaluate` in `src` (outside of the problem depot). I added comments to a few places, and updated the dev docs.
=> audit usages of `evaluate`

docs/make.jl, docs/src/examples/general_examples/worst_case_analysis.jl
locally the example was failing for me. I think it could depend on the exact random stream whether or not the matrix is positive-definite, as required by `quadform`; here, I ensure it.
The outer testset collects handy timings for us:
```
Test Summary:                                                                                                          | Pass  Total     Time
Examples                                                                                                               |   32     32  1m19.5s
/Users/eph/Convex.jl/docs/src/examples/general_examples/DCP_analysis.jl                                              |        None     0.0s
/Users/eph/Convex.jl/docs/src/examples/general_examples/basic_usage.jl                                               |        None …
```
=> add outer testset to docs and fix example

src/solution.jl, test/test_utilities.jl
Currently it returns `nothing`. I think this is nicer since then you get the solution summary printed after you do `solve!`, along with a summary of the problem. It's possible this can help users notice issues if they weren't looking at the problem, but did `solve!` in the REPL and noticed the output. In addition, looking at some of the examples like https://jump.dev/Convex.jl/dev/examples/mixed_integer/n_queens/, this would add more details to the example without needing a separate example block to show the problem first.
There is currently an explicit test that we return `nothing`, so I traced back the origin of that test to see why (in case there's some particular reason we need to return `nothing`). I believe it was added in https://github.com/jump-dev/Convex.jl/pull/62 originally, …
=> `solve!` returns the problem

docs/src/changelog.md
The code here deserves a release.
Approved by:
=> [docs] update Changelog with latest changes

src/Convex.jl, src/to_MOI.jl
This was initially a different thing from a `SparseTape`, since that was lazy, but they eventually merged to become the exact same thing. I think I meant to drop it from #504 but forgot.
=> cleanup: delete internal type `VectorAffineFunctionAsMatrix`

src/Convex.jl
This dramatically shortens the printing in some cases, like the problem in https://jump.dev/Convex.jl/dev/examples/mixed_integer/n_queens/. I think showing so many constraints isn't useful, and one can dig into the problem themselves if needed. Not really sure why I chose such a big value in the first place in https://github.com/jump-dev/Convex.jl/pull/345.
=> Drop default `MAXWIDTH` to 3 (from 15)

src/utilities/show.jl
noticed in https://jump.dev/Convex.jl/dev/examples/supplemental_material/paper_examples/
I think I'll do a quick pass tomorrow through the examples and spruce them up a bit
=> `show`: add underscores to number of atoms and coefficients

docs/src/examples/general_examples/basic_usage.jl, docs/src/examples/general_examples/chebyshev_center.jl, docs/src/examples/mixed_integer/n_queens.jl, docs/src/examples/optimization_with_complex_variables/povm_simulation.jl, src/deprecations.jl, src/problem_depot/problems/affine.jl, src/problem_depot/problems/socp.jl, src/problems.jl, test/test_utilities.jl
IMO it is kind of goofy, and doesn't match how the rest of Julia works which can make it confusing. There is also not much of a mathematical or translation purpose; I've never seen constraints written that way in a paper.
Also, I've updated the `Problem` constructors to be less picky about the types, which makes manual construction of the constraints vector (like `constraints = []; push!(...)` less annoying). I suspect the `p = minimize(...); p.constraints += ...` thing was partly to make the constructors work.
Lastly, I fixed a small bug: the field `constraints` was typed as an `Array`, which meant you could construct a `Matrix{Constraint}` as the `constraints` field in `Problem`, which would then break the new printing code. Here I've typed it as a `Vector`.
=> deprecate `+` on constraints

src/Constraint.jl, src/MOI_wrapper.jl
Second option of the two options listed in https://github.com/jump-dev/Convex.jl/pull/668
Closes https://github.com/jump-dev/Convex.jl/pull/668
=> Support vector sets in MOI wrapper

docs/src/examples/optimization_with_complex_variables/quantum_conditional_entropy.jl, docs/styles/config/vocabularies/jump-dev/accept.txt, src/reformulations/partialtranspose.jl
this is the second example from https://github.com/jump-dev/Convex.jl/pull/418#issuecomment-832190560
I thought it could be nice to have some examples using some of the CVXQUAD functionality. I put in a lot of quantum information theory preliminaries, but maybe we could trim some back if it's too much.
This example originally had 23s of formulation time and 4s solve time. I profiled and found `permutedims_matrix` was very slow and allocating (and it gets used a lot, since it is used for `transpose` and thus for `vcat`). I was able to optimize it by constructing the sparse matrix directly (in COO format). Now we have 3s formulation time and the same 4s solve time, which seems much more acceptable (maybe a little slow still, but I didn't see any other low hanging fruit).
BTW, here the …
=> Add quantum conditional entropy example

docs/src/examples/optimization_with_complex_variables/quantum_conditional_entropy.jl
=> Update quantum_conditional_entropy.jl to use kwarg `silent`

docs/src/changelog.md
I tried to catch everything since #589 
I would be in favor of releasing v0.16 after this!
=> Update changelog for recent PRs

docs/src/manual/complex-domain_optimization.md, src/atoms/QuadOverLinAtom.jl, test/test_atoms.jl
=> handle complex case in QuadOverLinAtom

src/ComplexTape.jl
noticed this when I was looking into #679
=> remove unused incorrect method

docs/src/manual/complex-domain_optimization.md, src/atoms/QolElemAtom.jl, src/atoms/QuadOverLinAtom.jl, test/test_atoms.jl
=> Fix formulation of Convex.sumsquares

docs/src/developer/contributing.md, src/problem_depot/problems/sdp.jl, src/reformulations/lieb_ando.jl
This is in fact the approach used in CVXQUAD (https://github.com/hfawzi/cvxquad/blob/master/lieb_ando.m), but we didn't have those yet at the time.
This way we don't have to create an atom! Pretty convenient.
Also: I noticed in many of the CVXQUAD-derived atoms, we expect some variables to be PSD, but don't check or enforce it. Could be something we might want to do.
closes #683
=> `lieb_ando`: use partially specified problem to get correct `vexity`

docs/src/changelog.md
=> Prep for v0.16.0

src/atoms/LogSumExpAtom.jl, src/problem_depot/problems/exp.jl, test/test_atoms.jl
=> Add dims argument to LogSumExpAtom

src/Constraint.jl, src/to_MOI.jl, test/test_constraints.jl
=> Fix distance_to_set for sets without a definition in MOI

src/real_operate.jl, test/test_utilities.jl
=> Fix incorrect type asssertion in real_operate

src/atoms/IndexAtom.jl, src/atoms/VcatAtom.jl, test/test_atoms.jl
Replacement for https://github.com/jump-dev/Convex.jl/pull/708
cc @RoyiAvital 
We'll leave the `Bool` methods as-is, but this now works as expected like the rest of Convex atoms.
=> Fix indexing AbstractExor with BitVector and BitMatrix

docs/src/manual/types.md
Adding a warning to avoid using `.` in expressions.
Closes https://github.com/jump-dev/Convex.jl/issues/716.
=> Add a Warning to Avoid Julia's Broadcatisng in Expressions

src/reformulations/log1p.jl, test/test_atoms.jl
=> Add support for Base.log1p
